#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-netty
Version  : 3.10.6.final
Release  : 5
URL      : https://repo1.maven.org/maven2/io/netty/netty/3.10.6.Final/netty-3.10.6.Final.jar
Source0  : https://repo1.maven.org/maven2/io/netty/netty/3.10.6.Final/netty-3.10.6.Final.jar
Source1  : https://repo1.maven.org/maven2/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.pom
Source2  : https://repo1.maven.org/maven2/io/netty/netty-all/4.0.52.Final/netty-all-4.0.52.Final.jar
Source3  : https://repo1.maven.org/maven2/io/netty/netty-all/4.0.52.Final/netty-all-4.0.52.Final.pom
Source4  : https://repo1.maven.org/maven2/io/netty/netty-all/4.1.17.Final/netty-all-4.1.17.Final.jar
Source5  : https://repo1.maven.org/maven2/io/netty/netty-all/4.1.17.Final/netty-all-4.1.17.Final.pom
Source6  : https://repo1.maven.org/maven2/io/netty/netty-codec-socks/4.0.24.Final/netty-codec-socks-4.0.24.Final.jar
Source7  : https://repo1.maven.org/maven2/io/netty/netty-codec-socks/4.0.24.Final/netty-codec-socks-4.0.24.Final.pom
Source8  : https://repo1.maven.org/maven2/io/netty/netty-parent/4.0.23.Final/netty-parent-4.0.23.Final.pom
Source9  : https://repo1.maven.org/maven2/io/netty/netty-parent/4.0.24.Final/netty-parent-4.0.24.Final.pom
Source10  : https://repo1.maven.org/maven2/io/netty/netty-parent/4.0.52.Final/netty-parent-4.0.52.Final.pom
Source11  : https://repo1.maven.org/maven2/io/netty/netty-parent/4.1.13.Final/netty-parent-4.1.13.Final.pom
Source12  : https://repo1.maven.org/maven2/io/netty/netty-parent/4.1.17.Final/netty-parent-4.1.17.Final.pom
Source13  : https://repo1.maven.org/maven2/io/netty/netty/3.10.5.Final/netty-3.10.5.Final.jar
Source14  : https://repo1.maven.org/maven2/io/netty/netty/3.10.5.Final/netty-3.10.5.Final.pom
Source15  : https://repo1.maven.org/maven2/io/netty/netty/3.10.6.Final/netty-3.10.6.Final.pom
Source16  : https://repo1.maven.org/maven2/io/netty/netty/3.6.2.Final/netty-3.6.2.Final.jar
Source17  : https://repo1.maven.org/maven2/io/netty/netty/3.6.2.Final/netty-3.6.2.Final.pom
Source18  : https://repo1.maven.org/maven2/io/netty/netty/3.7.0.Final/netty-3.7.0.Final.jar
Source19  : https://repo1.maven.org/maven2/io/netty/netty/3.7.0.Final/netty-3.7.0.Final.pom
Source20  : https://repo1.maven.org/maven2/io/netty/netty/3.9.9.Final/netty-3.9.9.Final.jar
Source21  : https://repo1.maven.org/maven2/io/netty/netty/3.9.9.Final/netty-3.9.9.Final.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause LGPL-2.1 MIT Public-Domain
Requires: mvn-netty-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-netty package.
Group: Data

%description data
data components for the mvn-netty package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/netty/netty/3.10.6.Final
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/io/netty/netty/3.10.6.Final/netty-3.10.6.Final.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/netty/netty-all/4.0.23.Final
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/netty/netty-all/4.0.52.Final
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/io/netty/netty-all/4.0.52.Final/netty-all-4.0.52.Final.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/netty/netty-all/4.0.52.Final
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/io/netty/netty-all/4.0.52.Final/netty-all-4.0.52.Final.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/netty/netty-all/4.1.17.Final
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/io/netty/netty-all/4.1.17.Final/netty-all-4.1.17.Final.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/netty/netty-all/4.1.17.Final
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/io/netty/netty-all/4.1.17.Final/netty-all-4.1.17.Final.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/netty/netty-codec-socks/4.0.24.Final
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/io/netty/netty-codec-socks/4.0.24.Final/netty-codec-socks-4.0.24.Final.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/netty/netty-codec-socks/4.0.24.Final
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/io/netty/netty-codec-socks/4.0.24.Final/netty-codec-socks-4.0.24.Final.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/netty/netty-parent/4.0.23.Final
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/io/netty/netty-parent/4.0.23.Final/netty-parent-4.0.23.Final.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/netty/netty-parent/4.0.24.Final
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/io/netty/netty-parent/4.0.24.Final/netty-parent-4.0.24.Final.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/netty/netty-parent/4.0.52.Final
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/io/netty/netty-parent/4.0.52.Final/netty-parent-4.0.52.Final.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/netty/netty-parent/4.1.13.Final
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/io/netty/netty-parent/4.1.13.Final/netty-parent-4.1.13.Final.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/netty/netty-parent/4.1.17.Final
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/io/netty/netty-parent/4.1.17.Final/netty-parent-4.1.17.Final.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/netty/netty/3.10.5.Final
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/io/netty/netty/3.10.5.Final/netty-3.10.5.Final.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/netty/netty/3.10.5.Final
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/io/netty/netty/3.10.5.Final/netty-3.10.5.Final.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/netty/netty/3.10.6.Final
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/io/netty/netty/3.10.6.Final/netty-3.10.6.Final.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/netty/netty/3.6.2.Final
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/io/netty/netty/3.6.2.Final/netty-3.6.2.Final.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/netty/netty/3.6.2.Final
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/io/netty/netty/3.6.2.Final/netty-3.6.2.Final.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/netty/netty/3.7.0.Final
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/io/netty/netty/3.7.0.Final/netty-3.7.0.Final.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/netty/netty/3.7.0.Final
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/io/netty/netty/3.7.0.Final/netty-3.7.0.Final.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/netty/netty/3.9.9.Final
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/io/netty/netty/3.9.9.Final/netty-3.9.9.Final.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/netty/netty/3.9.9.Final
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/io/netty/netty/3.9.9.Final/netty-3.9.9.Final.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.pom
/usr/share/java/.m2/repository/io/netty/netty-all/4.0.52.Final/netty-all-4.0.52.Final.jar
/usr/share/java/.m2/repository/io/netty/netty-all/4.0.52.Final/netty-all-4.0.52.Final.pom
/usr/share/java/.m2/repository/io/netty/netty-all/4.1.17.Final/netty-all-4.1.17.Final.jar
/usr/share/java/.m2/repository/io/netty/netty-all/4.1.17.Final/netty-all-4.1.17.Final.pom
/usr/share/java/.m2/repository/io/netty/netty-codec-socks/4.0.24.Final/netty-codec-socks-4.0.24.Final.jar
/usr/share/java/.m2/repository/io/netty/netty-codec-socks/4.0.24.Final/netty-codec-socks-4.0.24.Final.pom
/usr/share/java/.m2/repository/io/netty/netty-parent/4.0.23.Final/netty-parent-4.0.23.Final.pom
/usr/share/java/.m2/repository/io/netty/netty-parent/4.0.24.Final/netty-parent-4.0.24.Final.pom
/usr/share/java/.m2/repository/io/netty/netty-parent/4.0.52.Final/netty-parent-4.0.52.Final.pom
/usr/share/java/.m2/repository/io/netty/netty-parent/4.1.13.Final/netty-parent-4.1.13.Final.pom
/usr/share/java/.m2/repository/io/netty/netty-parent/4.1.17.Final/netty-parent-4.1.17.Final.pom
/usr/share/java/.m2/repository/io/netty/netty/3.10.5.Final/netty-3.10.5.Final.jar
/usr/share/java/.m2/repository/io/netty/netty/3.10.5.Final/netty-3.10.5.Final.pom
/usr/share/java/.m2/repository/io/netty/netty/3.10.6.Final/netty-3.10.6.Final.jar
/usr/share/java/.m2/repository/io/netty/netty/3.10.6.Final/netty-3.10.6.Final.pom
/usr/share/java/.m2/repository/io/netty/netty/3.6.2.Final/netty-3.6.2.Final.jar
/usr/share/java/.m2/repository/io/netty/netty/3.6.2.Final/netty-3.6.2.Final.pom
/usr/share/java/.m2/repository/io/netty/netty/3.7.0.Final/netty-3.7.0.Final.jar
/usr/share/java/.m2/repository/io/netty/netty/3.7.0.Final/netty-3.7.0.Final.pom
/usr/share/java/.m2/repository/io/netty/netty/3.9.9.Final/netty-3.9.9.Final.jar
/usr/share/java/.m2/repository/io/netty/netty/3.9.9.Final/netty-3.9.9.Final.pom
