#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-netty
Version  : 3.10.6.final
Release  : 1
URL      : https://repo1.maven.org/maven2/io/netty/netty/3.10.6.Final/netty-3.10.6.Final.jar
Source0  : https://repo1.maven.org/maven2/io/netty/netty/3.10.6.Final/netty-3.10.6.Final.jar
Source1  : https://repo1.maven.org/maven2/io/netty/netty/3.10.6.Final/netty-3.10.6.Final.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause LGPL-2.1
Requires: mvn-netty-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-netty package.
Group: Data

%description data
data components for the mvn-netty package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/netty/netty/3.10.6.Final
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/io/netty/netty/3.10.6.Final

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/netty/netty/3.10.6.Final
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/io/netty/netty/3.10.6.Final


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/io/netty/netty/3.10.6.Final/netty-3.10.6.Final.jar
/usr/share/java/.m2/repository/io/netty/netty/3.10.6.Final/netty-3.10.6.Final.pom
